/**
 * 한국어 문자열 (기본 언어). en.ts와 키 셋이 완전히 일치해야 한다.
 * 키 규약: 화면.항목 / tower.<id>.name|desc / enemy.<id>.name|desc / stage.<id>.name
 */
export const ko: Record<string, string> = {
  'app.name': '와가와가 디펜스',

  'title.logoTop': '와가와가',
  'title.logoBottom': '디펜스',
  'title.tapToStart': '탭하여 시작',
  'title.version': 'v{v}',

  'common.back': '뒤로',
  'common.ok': '확인',
  'common.cancel': '취소',
  'common.free': '무료',
  'common.max': '최대',
  'common.on': '켬',
  'common.off': '끔',

  'lobby.settings': '설정',
  'lobby.battle': '전투 시작!',
  'lobby.collection': '도감',
  'lobby.endless': '무한 모드',
  'lobby.endlessBest': '최고 {n}웨이브',
  'lobby.endlessNeedClear': '클리어 후 도전 가능',
  'lobby.progress': '웨이브 {n}/{m}',
  'lobby.cleared': '클리어!',
  'lobby.notStarted': '미도전',
  'lobby.locked': '스테이지 {n} 클리어 시 해금',
  'lobby.stageNo': '스테이지 {n}',

  'stage.1.name': '와가와가 초원',
  'stage.2.name': '우거진 정글',
  'stage.3.name': '이글이글 사막',
  'stage.4.name': '꽁꽁 설원',
  'stage.5.name': '부글부글 늪지',
  'stage.6.name': '으르렁 화산',

  'collection.title': '타워 도감',
  'collection.locked': '미보유',
  'collection.shards': '조각 {n}/{m}',
  'collection.starUp': '별 강화',
  'collection.cost': '조각 {s} · 호박 {a}',
  'collection.unlock': '해금하기',
  'collection.unlockAmber': '호박 {a}',
  'collection.unlockStage': '스테이지 {n} 클리어 시 해금',
  'collection.maxStar': '최대 강화 완료!',
  'collection.statDmg': '공격력',
  'collection.statRate': '공격 속도',
  'collection.statRange': '사거리',
  'collection.statCost': '배치 비용',
  'collection.statRateUnit': '{n}회/초',
  'collection.starBonusTitle': '별 1개당 보너스',
  'collection.bonusDmg': '공격력 +{n}%',
  'collection.bonusRate': '공속 +{n}%',
  'collection.bonusRange': '사거리 +{n}%',
  'collection.fxTitle': '특수 효과',
  'collection.fxSplash': '범위 피해',
  'collection.fxChain': '연쇄 공격',
  'collection.fxAuraDmg': '주변 지속 피해',
  'collection.fxAuraBuff': '주변 타워 강화',
  'collection.fxStatus.slow': '감속',
  'collection.fxStatus.burn': '화상',
  'collection.fxStatus.poison': '중독',
  'collection.fxStatus.stun': '기절',

  'settings.title': '설정',
  'settings.music': '음악',
  'settings.sfx': '효과음',
  'settings.lang': '언어',
  'settings.vibration': '진동',
  'settings.quality': '그래픽 품질',
  'settings.quality.auto': '자동',
  'settings.quality.low': '낮음',
  'settings.quality.med': '중간',
  'settings.quality.high': '높음',
  'settings.reset': '데이터 초기화',
  'settings.resetBody1': '모든 진행 상황이 삭제됩니다. 계속할까요?',
  'settings.resetBody2': '정말로요? 삭제하면 되돌릴 수 없어요!',
  'settings.resetFinal': '전부 삭제',
  'settings.credits': '모든 그래픽과 사운드는 코드로 만들었습니다.\n광고도 결제도 없는 무료 게임입니다.',

  'battle.wave': '웨이브',
  'battle.callWave': '웨이브 시작',
  'battle.earlyBonus': '조기 보너스 +{g}',
  'battle.prep': '{s}초 후 자동 시작',
  'battle.refresh': '새로고침',
  'battle.upgrade': '강화',
  'battle.sell': '판매',
  'battle.lv': 'Lv.{n}',
  'battle.targeting.first': '선두 우선',
  'battle.targeting.last': '후미 우선',
  'battle.targeting.strongest': '강한 적 우선',
  'battle.targeting.nearest': '가까운 적 우선',
  'battle.paused': '일시정지',
  'battle.resume': '계속하기',
  'battle.quit': '포기하기',
  'battle.quitBody': '전투를 포기하고 로비로 나갈까요?',
  'battle.auto': '자동',
  'battle.scenery.title': '방해 지형지물',
  'battle.scenery.desc': '치우면 이 자리에 타워를 지을 수 있어요',
  'battle.scenery.clear': '치우기',
  'battle.scenery.confirm': '정말?',
  'battle.scenery.confirmDesc': '한 번 더 누르면 {n} 골드가 빠져요 (되돌릴 수 없음)',
  'battle.scenery.needGold': '골드 {n} 부족',
  'battle.close': '닫기',
  'battle.lvOf': 'Lv.{n}/{m}',
  'battle.home.title': '홈타운',
  // 출격거리 = 부족원이 마을에서 몇 타일 앞까지 나가는가 (sim/allies.ts 규칙 2).
  // 이 줄에 없으면 "마을을 키우면 부족원이 더 멀리 나간다"는 설계가 화면 어디에도 없다
  'battle.home.stats': '체력 {hp} · 사거리 {r} · 출격거리 {s}',
  'battle.home.desc': '올리면 체력·공격력·사거리와 부족원 출격거리가 함께 커져요',
  'battle.home.next': '올리면 → 체력 {hp} · 공격 {d} · 사거리 {r} · 출격거리 {s}',
  'battle.home.confirmDesc': '한 번 더 누르면 {n} 골드가 빠져요 (되돌릴 수 없음)',
  'battle.home.maxed': '더 키울 수 없어요 (최대 단계)',
  'battle.ally.title': '부족 출동',
  // 상단 부족 칩 — 인원 표시이자 마을 패널로 가는 입구다 (출동 버튼은 패널 안에만 있다)
  'battle.ally.pillHint': '나가 있는 부족원 — 눌러서 마을 열기 (출동·강화)',
  // 세 종이 공유하는 규칙 — 버튼마다 세 번 적지 않고 여기 한 줄로 모은다
  'battle.ally.rules': '{s}초 뒤 마을로 돌아가요 · 살아 돌아오면 정가의 {p}% 환급 · 동시 {m}명까지',
  'ally.clubber.name': '몽둥이꾼',
  // 마릿수는 balance.ALLY_BLOCK_CAPACITY 에서 넘어온다 (규칙이 바뀌면 문구도 따라 바뀐다)
  'ally.clubber.desc': '싸고 발 빠른 근접. 최대 {n}마리의 발을 묶어요',
  'ally.slinger.name': '돌팔매꾼',
  'ally.slinger.desc': '뒤에서 던져요. 공중도 맞히지만 아무도 막지 못해요',
  'ally.guardian.name': '파수꾼',
  'ally.guardian.desc': '방패와 갑옷. {n}마리에게 둘러싸여도 수명을 채워요',
  // --- 웨이브 미리보기 띠 (prep 전용) --------------------------------------
  // 칩에는 **적 이름을 쓰지 않는다** — '안킬로사우루스'가 390px에서 깨진다.
  // 이름은 탭 후 상세에만 나오고, 칩은 아이콘 + 마릿수 + 특성 배지로만 말한다.
  'battle.preview.title': '다음 웨이브',
  'battle.preview.expand': '자세히 보기',
  'battle.preview.collapse': '접기',
  'battle.preview.demand': '내 타워가 얼마나 듣나',
  'battle.preview.more': '+{n}종',
  'battle.preview.hp': '체력 {n} × {c}마리',
  'battle.preview.good': '잘 들어요',
  'battle.preview.bad': '안 들어요',
  // 없는 답을 알려주는 것은 정보가 아니라 좌절이다 — 그래서 **내 덱 안**에서만 찾는다
  'battle.preview.noAnswer': '지금 덱에는 잘 듣는 카드가 없어요',
  'battle.preview.plain': '특별한 방어는 없어요',
  'battle.preview.weakVs': '{n} 상대로 약해요',

  // 특성 — 이름은 배지에, 설명은 상세 한 줄에 쓴다
  'trait.air.name': '하늘',
  'trait.air.desc': '날아서 지나가요 — 공중을 때리는 타워만 닿아요',
  'trait.shield.name': '방패',
  'trait.shield.desc': '처음 몇 대를 통째로 무시해요 — 자주 때려서 벗겨내세요',
  'trait.armor.name': '장갑',
  'trait.armor.desc': '한 대마다 {n}씩 깎여요 — 작게 여러 번 때리는 타워가 손해예요',
  'trait.hide.name': '가죽',
  'trait.hide.desc': '한 대에 {n}까지만 들어가요 — 크게 한 방 때리는 타워가 손해예요',
  'trait.splash.name': '흩어짐',
  'trait.splash.desc': '터지는 피해가 잘 안 들어가요 — 폭발 말고 직접 때리세요',
  'trait.heal.name': '치유',
  'trait.heal.desc': '주변 동료를 계속 되살려요 — 이쪽을 먼저 잡으세요',
  'trait.raid.name': '습격',
  'trait.raid.desc': '기지가 아니라 내 타워를 부수러 와요 — 길에서 떨어뜨려 지으세요',
  'trait.enrage.name': '격노',
  'trait.enrage.desc': '체력이 떨어지면 훨씬 빨라져요 — 느리게 만들어 두세요',

  'battle.waveBanner': '웨이브 {n}',
  'battle.finalWaveBanner': '마지막 웨이브!',
  'battle.bossBanner': '보스 출현!',

  'result.victory': '승리!',
  'result.defeat': '패배…',
  'result.wave': '도달 웨이브',
  'result.kills': '처치',
  'result.amber': '호박',
  'result.shards': '타워 조각',
  'result.retry': '다시하기',
  'result.lobby': '로비로',
  'result.next': '다음 스테이지',
  'result.firstClear': '첫 클리어 보너스!',
  'result.endless': '무한 모드',

  'tower.spear.name': '창던지기 움막',
  'tower.spear.desc': '부족 사냥꾼이 창을 슝슝! 값싸고 어디서나 든든한 기본 타워.',
  'tower.catapult.name': '돌 투석기',
  'tower.catapult.desc': '큰 바위를 날려 뭉친 적을 한꺼번에! 공중의 적은 맞히지 못해요.',
  'tower.lightning.name': '번개 토템',
  'tower.lightning.desc': '찌릿! 번개가 적 사이를 튀며 연쇄 피해를 줘요.',
  'tower.brazier.name': '화염 모닥불',
  'tower.brazier.desc': '주변의 적을 계속 태우는 불의 오라. 가까이 오면 뜨거워요!',
  'tower.frost.name': '얼음 크리스탈',
  'tower.frost.desc': '차가운 기운으로 적의 발을 꽁꽁 얼려 느리게 만들어요.',
  'tower.poison.name': '독가시 덩굴',
  'tower.poison.desc': '독가시를 쏘아 중독시켜요. 맞은 적은 서서히 아파요.',
  'tower.ballista.name': '상아 발리스타',
  'tower.ballista.desc': '거대한 상아 화살로 단일 적에게 강력한 한 방!',
  'tower.drum.name': '전쟁북',
  'tower.drum.desc': '둥둥둥! 북소리로 주변 타워의 공격력과 속도를 올려줘요.',

  'enemy.raptor.name': '랩터',
  'enemy.raptor.desc': '빠른 발로 달려드는 성질 급한 사냥꾼.',
  'enemy.compy.name': '콤피 떼',
  'enemy.compy.desc': '작지만 숫자로 밀어붙이는 꼬마 공룡 무리.',
  'enemy.trike.name': '트리케라톱스',
  'enemy.trike.desc': '세 개의 뿔과 단단한 몸집의 탱커.',
  'enemy.ptera.name': '프테라노돈',
  'enemy.ptera.desc': '하늘로 날아 지상 공격을 피해 다녀요.',
  'enemy.ankylo.name': '안킬로사우루스',
  'enemy.ankylo.desc': '갑옷 같은 등딱지로 피해를 줄여요.',
  'enemy.boar.name': '원시 멧돼지',
  'enemy.boar.desc': '다치면 더 빨라지는 성난 멧돼지.',
  'enemy.warrior.name': '부족 전사',
  'enemy.warrior.desc': '방패로 몇 번의 공격을 막아내요. 멈춰 서서 창을 던지기도 해요.',
  'enemy.shaman.name': '부족 주술사',
  'enemy.shaman.desc': '주변 동료를 치유하는 성가신 주술사.',
  'enemy.blade.name': '부족 투창병',
  'enemy.blade.desc': '제일 먼저 달려와 멈춰 서서 짧은 창을 쉴 새 없이 던져요!',
  'enemy.lancer.name': '부족 큰창잡이',
  'enemy.lancer.desc': '버티고 서서 무거운 장창을 던져요. 가죽갑옷 덕에 오래 버텨요.',
  'enemy.archer.name': '부족 궁수',
  'enemy.archer.desc': '멀리서 멈춰 서서 활을 쏘아 타워를 갉아요. 몸은 약해요.',
  'enemy.hexer.name': '부족 주술 저주사',
  'enemy.hexer.desc': '가장 멀리서 저주를 던져 타워를 잠시 침묵시켜요. 저주에 걸린 타워는 쏘지 못해요!',
  'enemy.mammoth.name': '매머드',
  'enemy.mammoth.desc': '땅을 울리며 걷는 거대한 털북숭이.',
  'enemy.spino.name': '스피노사우루스',
  'enemy.spino.desc': '등지느러미를 세운 사나운 미니보스.',
  'enemy.trex.name': '티라노사우루스',
  'enemy.trex.desc': '모든 것을 짓밟는 폭군, 최종 보스.',
  'enemy.golem.name': '화산 골렘',
  'enemy.golem.desc': '용암이 흐르는 바위 거인. 화산에서만 나타나요.',
};
